name: Linting Python Code

on: push

jobs:
  python-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Super-Linter
        uses: github/super-linter@v4.8.4
        env:
          VALIDATE_PYTHON: true
